apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  namespace: angular-recipe
spec:
  replicas: 4
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
      - name: client
        image: kofimorrison/angular-recipe
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
